#pragma once
#include <cgate.h>
#pragma pack(push, 4)

//generated by schemetool.exe

struct plaza_part
{
	signed long long replID; // i8
	signed long long replRev; // i8
	signed long long replAct; // i8
	char client_code[8]; // c7
	char coeff_go[11]; // d16.5					 
	char money_amount[15]; // d26.2
	char money_free[15]; // d26.2
	char money_blocked[15]; // d26.2					
	char fee[15]; // d26.2

};

struct plaza_fut_vm
{
	signed long long replID; // i8
	signed long long replRev; // i8
	signed long long replAct; // i8
	signed int isin_id; // i4
	signed int sess_id; // i4
	char client_code[8]; // c7
	char vm[11]; // d16.5
	char vm_real[11]; // d16.5

};

struct plaza_position
{
	signed long long replID; // i8
	signed long long replRev; // i8
	signed long long replAct; // i8
	signed int isin_id; // i4
	char client_code[8]; // c7
	signed int open_qty; // i4
	signed int buys_qty; // i4
	signed int sells_qty; // i4
	signed int pos; // i4
	char net_volume_rur[15]; // d26.2
	char waprice[11]; // d16.5

};


struct plaza_fut_sess_contents
{
	signed long long replID; // i8
	signed long long replRev; // i8
	signed long long replAct; // i8
	signed int sess_id; // i4
	signed int isin_id; // i4
	char short_isin[26]; // c25
	char isin[26]; // c25
	char name[76]; // c75
	signed int inst_term; // i4
	char code_vcb[26]; // c25
	signed char is_limited; // i1
	char limit_up[11]; // d16.5
	char limit_down[11]; // d16.5
	char old_kotir[11]; // d16.5
	char buy_deposit[10]; // d16.2
	char sell_deposit[10]; // d16.2
	signed int roundto; // i4
	char min_step[11]; // d16.5
	signed int lot_volume; // i4
	char step_price[11]; // d16.5
	struct cg_time_t d_pg; // t
	signed char is_spread; // i1
	char coeff[7]; // d9.6
	struct cg_time_t d_exp; // t
	signed char is_percent; // i1
	char percent_rate[5]; // d6.2
	char last_cl_quote[11]; // d16.5
	signed int signs; // i4
	signed char is_trade_evening; // i1
	signed int ticker; // i4
	signed int state; // i4
	signed char price_dir; // i1
	signed int multileg_type; // i4
	signed int legs_qty; // i4
	char step_price_clr[11]; // d16.5
	char step_price_interclr[11]; // d16.5
	char step_price_curr[11]; // d16.5

};



struct plaza_my_orders_log
{
	signed long long replID; // i8
	signed long long replRev; // i8
	signed long long replAct; // i8
	signed long long id_ord; // i8
	signed int sess_id; // i4
	signed int isin_id; // i4
	signed int amount; // i4
	signed int amount_rest; // i4
	signed long long id_deal; // i8
	signed int status; // i4
	char price[11]; // d16.5
	struct cg_time_t moment; // t
	unsigned long long moment_ns; // u8
	signed char dir; // i1
	signed char action; // i1
	char deal_price[11]; // d16.5
	char client_code[8]; // c7
	char comment[21]; // c20
	signed int ext_id; // i4
	struct cg_time_t date_exp; // t
	signed long long id_ord1; // i8
	struct cg_time_t local_stamp; // t

};


struct plaza_my_multileg_orders_log
{
	signed long long replID; // i8
	signed long long replRev; // i8
	signed long long replAct; // i8
	signed long long id_ord; // i8
	signed int sess_id; // i4
	signed int isin_id; // i4
	signed int amount; // i4
	signed int amount_rest; // i4
	signed long long id_deal; // i8
	signed int status; // i4
	char price[11]; // d16.5
	struct cg_time_t moment; // t
	unsigned long long moment_ns; // u8
	signed char dir; // i1
	signed char action; // i1
	char deal_price[11]; // d16.5
	char rate_price[11]; // d16.5
	char swap_price[11]; // d16.5
	char client_code[8]; // c7
	char login_from[21]; // c20
	char comment[21]; // c20
	signed char hedge; // i1
	signed char trust; // i1
	signed int ext_id; // i4
	char broker_to[8]; // c7
	char broker_to_rts[8]; // c7
	char broker_from_rts[8]; // c7
	struct cg_time_t date_exp; // t
	signed long long id_ord1; // i8
	struct cg_time_t local_stamp; // t

};



struct plaza_multileg_deal
{
	signed long long replID; // i8
	signed long long replRev; // i8
	signed long long replAct; // i8
	signed int sess_id; // i4
	signed int isin_id; // i4
	signed long long id_deal; // i8
	signed long long id_ord_buy; // i8
	signed long long id_ord_sell; // i8
	signed int amount; // i4
	char price[11]; // d16.5
	char rate_price[11]; // d16.5
	char swap_price[11]; // d16.5
	char buyback_amount[10]; // d16.2
	struct cg_time_t moment; // t
	signed char nosystem; // i1
	signed int status_buy; // i4
	signed int status_sell; // i4
	signed int ext_id_buy; // i4
	signed int ext_id_sell; // i4
	char code_buy[8]; // c7
	char code_sell[8]; // c7
	char comment_buy[21]; // c20
	char comment_sell[21]; // c20
	signed char trust_buy; // i1
	signed char trust_sell; // i1
	signed char hedge_buy; // i1
	signed char hedge_sell; // i1
	char code_rts_buy[8]; // c7
	char code_rts_sell[8]; // c7

};

struct plaza_user_deal
{
	signed long long replID; // i8
	signed long long replRev; // i8
	signed long long replAct; // i8
	signed int sess_id; // i4
	signed int isin_id; // i4
	signed long long id_deal; // i8
	signed long long id_deal_multileg; // i8
	signed int pos; // i4
	signed int amount; // i4
	signed long long id_ord_buy; // i8
	signed long long id_ord_sell; // i8
	char price[11]; // d16.5
	struct cg_time_t moment; // t
	signed char nosystem; // i1
	signed int status_buy; // i4
	signed int status_sell; // i4
	signed int ext_id_buy; // i4
	signed int ext_id_sell; // i4
	char code_buy[8]; // c7
	char code_sell[8]; // c7
	char comment_buy[21]; // c20
	char comment_sell[21]; // c20
	signed char trust_buy; // i1
	signed char trust_sell; // i1

};


struct plaza_fut_common
{
	signed long long replID; // i8
	signed long long replRev; // i8
	signed long long replAct; // i8
	signed int sess_id; // i4
	signed int isin_id; // i4
	char best_buy[11]; // d16.5
	signed int amount_buy; // i4
	signed int orders_buy_qty; // i4
	signed int orders_buy_amount; // i4
	char best_sell[11]; // d16.5
	signed int amount_sell; // i4
	signed int orders_sell_qty; // i4
	signed int orders_sell_amount; // i4
	char open_price[11]; // d16.5
	char close_price[11]; // d16.5
	char price[11]; // d16.5
	char trend[11]; // d16.5
	signed int amount; // i4
	struct cg_time_t deal_time; // t
	unsigned long long deal_time_ns; // i8
	char min_price[11]; // d16.5
	char max_price[11]; // d16.5
	char avr_price[11]; // d16.5
	signed int contr_count; // i4

};

#pragma pack(pop)